export const userData = [
	{
		key: "1",
		firstName: "John",
		lastName: "Brown",
		email: "johnbrown@mymail.com",
		hoursStudied: 100,
		phoneNumber: 919919199,
		groups: ["primary"],
	},
	{
		key: "2",
		firstName: "Jim",
		lastName: "Green",
		email: "jimgreen21@mymail.com",
		hoursStudied: 40,
		phoneNumber: 3154314129,
		groups: ["secondary"],
	},
	{
		key: "3",
		firstName: "Joe",
		lastName: "Black",
		email: "joeblack@mymail.com",
		hoursStudied: 90,
		phoneNumber: 1324222321,
		groups: ["secondary"],
	},

	{
		key: "4",
		firstName: "pigeon",
		lastName: "john",
		email: "johnpigeon32@mymail.com",
		hoursStudied: 120,
		phoneNumber: 343422251,
		groups: ["primary"],
	},
	{
		key: "5",
		firstName: "Carol",
		lastName: "Clark",
		email: "carolclark64@mymail.com",
		hoursStudied: 190,
		phoneNumber: 232300434,
		groups: ["secondary"],
	},
	{
		key: "6",
		firstName: "michael",
		lastName: "brown",
		email: "michaelbrown034@mymail.com",
		hoursStudied: 130,
		phoneNumber: 153529221,
		groups: ["secondary"],
	},
	{
		key: "7",
		firstName: "ron",
		lastName: "done",
		email: "ronedone24@mymail.com",
		hoursStudied: 60,
		phoneNumber: 3433431323,
		groups: ["primary"],
	},
	{
		key: "8",
		firstName: "karen",
		lastName: "crow",
		email: "karencrow001@mymail.com",
		hoursStudied: 120,
		phoneNumber: 434021324,
		groups: ["secondary"],
	},
	{
		key: "9",
		firstName: "James",
		lastName: "White",
		email: "jameswhite20@mymail.com",
		hoursStudied: 160,
		phoneNumber: 332423431,
		groups: ["secondary"],
	},
	{
		key: "10",
		firstName: "jack",
		lastName: "jill",
		email: "jackjill44@mymail.com",
		hoursStudied: 150,
		phoneNumber: 5893422271,
		groups: ["primary"],
	},
	{
		key: "11",
		firstName: "mary",
		lastName: "gray",
		email: "marygray25@mymail.com",
		hoursStudied: 170,
		phoneNumber: 8944477251,
		groups: ["secondary"],
	},
	{
		key: "12",
		firstName: "cate",
		lastName: "show",
		email: "cateshow32@mymail.com",
		hoursStudied: 110,
		phoneNumber: 724222321,
		groups: ["primary"],
	},
];
